### PR TITLE
make sure register.bat works on 64 bit systems

### PR DESCRIPTION
**Pull request by reinsch82**

### CODE REVIEW

**Comment by jdiamond** [comment]
Hi, thanks for the PR.

What is the /reg:32 for? The VM I was running in is 64-bit and I did see it working there (after many frustrating hours and finally making a custom Node build).

Sorry about leaving that logging stuff in. I was so excited it finally worked.

**Comment by reinsch82** [comment]
you are right, I was under the impression that as chrome is a 32 bit process it would look things up under the 32 bit part of the registry. that is what the /reg:32 would have been for, to make sure it ends up there.
but it also works as it was.
It served us as a good starting point for our extension, so I wanted to return something :)
thx

**Comment by yf-hk** [comment]
Hi @jdiamond, could you share how did you make a custom node build?

**Comment by jdiamond** [comment]
@andyhu I think I just cloned the Node.js repository on GitHub and made the build the way they document.

The custom build was necessary because of a bug in Node.js at the time. I didn't modify any code, just built a newer, unreleased version. I think I was on 0.10.x and 0.12.x wasn't out yet.

If you're using a modern version of Node.js, I assume it shouldn't be necessary to use the custom build anymore. I'll test it when I get a chance.

**Comment by yf-hk** [comment]
Thanks very much for the answer! @jdiamond

**Pull request closed without merging**
